{{- if .Values.fileStorage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "board-service.fullname" . }}-files
  labels:
    {{- include "board-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.fileStorage.persistence.storageClass }}
  storageClassName: {{ .Values.fileStorage.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.fileStorage.persistence.size }}
{{- end }}
