apiVersion: v2
name: notification-service
description: Notification Service for LMS - Push, Email, SMS Notifications
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: "9.14.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
