apiVersion: v2
name: organization-service
description: Organization Service for LMS - Manages Colleges, Departments, Academic Terms
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: "9.14.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
