apiVersion: v2
name: catalog-service
description: Catalog Service - Subjects & Course Types Management
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: mysql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
