apiVersion: v1
kind: Secret
metadata:
  name: {{ include "assessment-service.fullname" . }}-secret
  labels:
    {{- include "assessment-service.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.secrets.dbUsername | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
