apiVersion: v2
name: assessment-service
description: LMS Assessment Service Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - lms
  - assessment
  - quiz
  - exam
  - spring-boot
maintainers:
  - name: MZC LMS Team
    email: lms@mzc.com
