apiVersion: v1
kind: Secret
metadata:
  name: {{ include "learning-progress-service.fullname" . }}-secrets
  labels:
    {{- include "learning-progress-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
