apiVersion: v1
kind: Secret
metadata:
  name: {{ include "media-service.fullname" . }}-secret
  labels:
    {{- include "media-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
