apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-service.fullname" . }}
  labels:
    {{- include "media-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.nginx.enabled }}
    - port: {{ .Values.service.nginxPort }}
      targetPort: nginx
      protocol: TCP
      name: nginx
    {{- end }}
  selector:
    {{- include "media-service.selectorLabels" . | nindent 4 }}
